// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olxgjuqibzzjvatwhuyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seGdqdXFpYnp6anZhdHdodXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMDg0ODQsImV4cCI6MjA0OTg4NDQ4NH0.RauiX7y47QlyOyWnAxPnLw27YokOhv5XG_PFG4XEtXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);